# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcc5b20d9ae305329c428483dc79865ce597608913c30f3f2d5f4ed88d0b9529626f0607bf7ce374b9bbd78e158c0ed0bc6af9d80a3c71f16721f38c540b4ca6

test:
  secret_key_base: fb4340c458fa543bc172d650c6bd18e4c793940bc7b17c6dd1081b631ee5cca6cad6470670b2532c804fda5035b0fe6b8bb3bb14c25dc0753c4beecc74ced34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
